### PR TITLE
UPGRADE ArduinoJson "^7.0.3" + USE recommended JsonDocument

### PR DESCRIPTION
**Pull request by oopen**
Tested on my ESP32 working.

### CODE REVIEW

**Comment by MartinVerges** [comment]
Thank you for this patch

**Comment by oopen** [comment]
Pleasure, thank for this useful lib !

**Comment by oopen** [comment]
Hello, could you update lib to v1.1.2 ? and push to PlatformIO ?

https://github.com/MartinVerges/esp32-wifi-manager/issues/8

**Comment by MartinVerges** [comment]
done

**Pull request merged**
